name: Nussbaum
layout_spectrum: 0.29774430324323475
typography_spectrum: 0.16703228931874037
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.5012855436652899
  lightness: 0.15568603877909482
  saturation: 0.14612851128913462
  rhythmicContrast: 0.5533338524401188
purpose: []
title: Explore With Me
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
coverPrefs:
  filter: false
